### PR TITLE
Update comparison signals of electric machine examples

### PR DESCRIPTION
**Pull request by christiankral**
Refs https://github.com/modelica/ModelicaStandardLibrary/issues/3587

Creating the very same changes as in https://github.com/modelica/ModelicaStandardLibrary/pull/3497/files for MSL 3.2.3:

- Remove zero sequence currents
- Add phase currents instead

### CODE REVIEW

**Review by beutlich — COMMENTED** [review]
The PR should target v3.2.3+build.4.

**Review by casella — APPROVED** [review]
Looks good to me

**Review by beutlich — CHANGES_REQUESTED** [review]
The PR targets the outdated branch v3.2.3. It should however be based on v3.2.3+build.4, which contains all  my latest fixes for https://github.com/modelica/ModelicaStandardLibrary/issues/2968.

**Comment by christiankral** [comment]
This PR is replaced by #3

**Comment by HansOlsson** [comment]
@casella wrote:
> I also see that branch v4.0.0 is 16 commits behind master. Should we merge all those commits into master, so they can be used for the next release as well? I don't think they are specific of 4.0.0, are they?

@beutlich replied:
> master is not the default branch of this repository. All the reference results live in the individual branches.

This made me a bit confused, and if someone else was as well I think it is best to clarify it:
- The branch master is 16 commits behind v4.0.0; not the other way round as indicated above. 
- The stats are a bit odd for this repo as all comparisons in GitHub of commits behind/ahead are in comparison to the default branch (v4.0.0).

**Comment by casella** [comment]
@HansOlsson wrote
>     * The branch master is 16 commits behind v4.0.0; not the other way round as indicated above.

Of course, sorry for adding even more confusion, it was so odd for me that I referred to it as I thought it should have been...

**Comment by casella** [comment]
In any case, I remain confused about the master branch not being the default. It is not clear to me:
- what is the point of having a master branch that is not the default
- how should it be kept up-to-date
- what is it used for?

**Pull request closed without merging**
