### PR TITLE
Delete ModelicaTest/Media/TestOnly/R134a_setState_pTX/MoistAir.csv

### PR DESCRIPTION
**Pull request by maltelenz**
This file is misplaced.

### CODE REVIEW

**Comment by beutlich** [comment]
Already in v4.0.0: https://github.com/modelica/MAP-LIB_ReferenceResults/tree/v4.0.0/ModelicaTest/Media/TestOnly/R134a_setState_pTX

Can I/you retarget your PR?

**Comment by maltelenz** [comment]
I guess we need an additional PR for 4.0.0 if we want to fix that branch as well?

**Comment by beutlich** [comment]
> I guess we need an additional PR for 4.0.0 if we want to fix that branch as well?

Do not get it. If it is fixed in v4.0.0 and not touched by #8, it will be fine.

**Comment by maltelenz** [comment]
> Do not get it. If it is fixed in v4.0.0 and not touched by #8, it will be fine.

Really? There is already a https://github.com/modelica/MAP-LIB_ReferenceResults/tree/v4.1.0 branch. How would a PR against 4.0.0 fix it on the 4.1.0 branch?

**Comment by beutlich** [comment]
Isn't v41.0.0 not branched off of v4.0.0? If yes, v4.1.0 can be rebased.

**Comment by maltelenz** [comment]
> v4.1.0 can be rebased.

I wasn't aware we were rebasing branches in this repository. In fact, I have no idea what workflow we are following in this repository...

**Comment by beutlich** [comment]
OK, resolved in v4.0.0 by https://github.com/modelica/MAP-LIB_ReferenceResults/commit/d6a2b9b20426bbff1a6a5a1f29bb4c5e50d0e57a.

**Comment by beutlich** [comment]
> If yes, v4.1.0 can be rebased.

Done.

**Pull request closed without merging**
