### PR TITLE
Remove duplicates in SignalNames of 10 examples of ModelicaTest

### PR DESCRIPTION
**Pull request by MatthiasBSchaefer**
In the following Example-Models of ModelicaTest there were some signals twice:

ModelicaTest/Blocks/Limiters
ModelicaTest/Fluid/Dissipation/Verifications/HeatTransfer/Channel/kc_evenGapLaminar
ModelicaTest/Fluid/Dissipation/Verifications/PressureLoss/Orifice/dp_suddenChange_DPMFLOW
ModelicaTest/Fluid/Dissipation/Verifications/PressureLoss/Orifice/dp_thickEdgedOverall_DPMFLOW
ModelicaTest/MultiBody/Joints/JointRRP
ModelicaTest/MultiBody/Joints/JointRRR
ModelicaTest/MultiBody/Joints/JointSSP
ModelicaTest/MultiBody/Joints/JointSSR
ModelicaTest/MultiBody/Joints/JointUSP
ModelicaTest/MultiBody/Joints/JointUSR

This caused problems when using Compare.exe to compare the results. So i removed the duplicates.

### CODE REVIEW

**Review by beutlich — COMMENTED** [review]
1. Could you please target the changes of the comparisonSignals.txt files to https://github.com/modelica/ModelicaStandardLibrary repo since this repo is the true source.

2. I do not believe that the changes to the CSV files are necessary as Compare.exe should be able to handle this.

**Comment by MatthiasBSchaefer** [comment]
2.) CSV Compare version 2.0.3.0 (latest commit) gives:
 2023-08-10Z09:59:51 [       Error ] Exception said: Error parsing the CSV file "xxxx\MAP-LIB_ReferenceResults\ModelicaTest\Blocks\Limiters\Limiters.csv". The result slewRateLimiter.y is already in the list (maybe you set no or a wrong delimiter for the parser? I used ",").
 I'll open a issue in the corresponding repo

**Comment by beutlich** [comment]
Let me try to reproduce first. Which is the command of Compare.exe you are using?

**Comment by MatthiasBSchaefer** [comment]
Compare.exe -m csvFileCompare -v 4 -d , -t 2e-3 --comparisonflag -o -b -r .  xxx\MAP-LIB_ReferenceResults\ModelicaTest\Blocks\Limiters\Limiters.csv  ModelicaTest.Blocks.Limiters\WorkDir\result.csv

where the latter one is a current simulation result of the example

**Comment by beutlich** [comment]
OK, can reproduce. No need to create ticket for csv-compare tool.

**Review by beutlich — CHANGES_REQUESTED** [review]
Can you please keep the trailing new-line in the 10 changed comparisonSignals.txt files as already done in https://github.com/modelica/ModelicaStandardLibrary/pull/4179. With that change it is acceptable for me and should be merged.

**Comment by MatthiasBSchaefer** [comment]
The comparisonSignals.txt files now have again the newline-character at end-of-file.

**Review by beutlich — APPROVED** [review]
LGTM. Thank you!

**Pull request merged**
